# Generated by Django 5.0.4 on 2025-06-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bill_reference',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
