# Generated by Django 5.0.4 on 2025-06-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_bill_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='bill_reference',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentReference',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
