# Generated by Django 5.0.4 on 2025-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_bill_reference_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
