# Generated by Django 5.0.4 on 2024-09-19 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(default='slug', null=True)),
                ('description', models.CharField(max_length=200)),
                ('rate', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255, null=True)),
                ('rc_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('country', models.CharField(default='Nigeria', max_length=300)),
                ('state', models.CharField(default='Lagos State', max_length=300)),
                ('address', models.CharField(max_length=300, null=True)),
                ('company_logo', models.ImageField(blank=True, default='uploads/default.png', upload_to='uploads/logo/')),
                ('bio_data', models.TextField(blank=True)),
                ('date_enrolled', models.DateField(blank=True, null=True)),
                ('is_tax_admin', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('1', 'Taxpayer'), ('2', 'Admin1'), ('3', 'Admin2'), ('4', 'Admin3')], default='1', max_length=20)),
                ('is_disabled', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='account.sector')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
