# Generated by Django 5.0.4 on 2025-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, default='uploads/logo/default.png', upload_to='uploads/logo/'),
        ),
    ]
