# Generated by Django 5.0.4 on 2025-09-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, default='media/uploads/logo/default.png', upload_to='uploads/logo/'),
        ),
    ]
