services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers=4 --threads=2 --timeout=120
    volumes:
      - .:/app
      - ./static:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env.production
    depends_on:
      - redis
    ports:
      - "8000:8000"
    restart: always

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A core worker -l info --concurrency=4 --max-tasks-per-child=1000 --max-memory-per-child=200000
    volumes:
      - .:/app
    env_file:
      - .env.production
    depends_on:
      - redis
    restart: always

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env.production
    depends_on:
      - redis
    restart: always

  # flower:
  #   image: mher/flower
  #   container_name: flower
  #   command: flower --broker=redis://redis:6379/0 --port=5555
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env.production
  #   restart: always

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    # ports:
    #   - "6379:6379"
    restart: always

volumes:
  redis_data:
