version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tax_net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    # command: gunicorn tax-service.core.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - .:/app/tax-service
      - static_volume:/app/tax-service/staticfiles
      - media_volume:/app/tax-service/media
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/tax-service

    env_file:
      - .env.production
    depends_on:
      - redis
    networks:
      - tax_net

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A core worker --loglevel=info --concurrency=4
    volumes:
      - .:/app/tax-service
    env_file:
      - .env.production
    depends_on:
      - redis
    networks:
      - tax_net

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app/tax-service
    env_file:
      - .env.production
    depends_on:
      - redis
    networks:
      - tax_net

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flower
    command: celery -A core flower --broker=redis://redis:6379/0 --basic_auth=admin:admin
    ports:
      - "5555:5555"
    volumes:
      - .:/app/tax-service
    env_file:
      - .env.production
    depends_on:
      - redis
      - celery_worker
    networks:
      - tax_net

volumes:
  redis_data:
  static_volume:
  media_volume:

networks:
  tax_net:
    driver: bridge
