[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_tests.py
# addopts = -rP
addopts = --reuse-db --nomigrations --ds=core.settings
env =
    DJANGO_ALLOW_ASYNC_UNSAFE=true
# asyncio_mode = auto
