# Generated by Django 5.0.4 on 2024-09-19 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infra_name', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.CharField(max_length=200, null=True)),
                ('is_exisiting', models.BooleanField(default=False)),
                ('infra', models.CharField(max_length=1000)),
                ('amount_due', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('application_fee', models.PositiveIntegerField(default=0)),
                ('admin_fee', models.PositiveIntegerField(default=0)),
                ('site_assessment', models.PositiveIntegerField(default=0)),
                ('annual_fee', models.PositiveIntegerField(default=0)),
                ('remittance', models.PositiveIntegerField(default=0)),
                ('waiver_applied', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('total_due', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DEMAND NOTICE', 'Demand Notice'), ('UNDISPUTED UNPAID', 'Undisputed Unpaid'), ('UNDISPUTED PAID', 'Undisputed Paid'), ('REVISED', 'Revised'), ('RESOLVED', 'Resolved')], default='UNPAID', max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('year_installed', models.PositiveIntegerField(default=2024)),
                ('upload_application_letter', models.FileField(blank=True, null=True, upload_to='uploads/applications/')),
                ('upload_asBuilt_drawing', models.FileField(blank=True, null=True, upload_to='uploads/drawings/')),
                ('is_existing', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('referenceid', models.CharField(max_length=20, null=True)),
                ('cost', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to=settings.AUTH_USER_MODEL)),
                ('infra_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_type', to='tax.infrastructuretype')),
            ],
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.CharField(max_length=20)),
                ('remitted_amount', models.IntegerField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='uploads/receipts/')),
                ('approved', models.BooleanField(default=False)),
                ('apply_for_waver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remit_comp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.CharField(max_length=20)),
                ('wave_amount', models.IntegerField(default=0)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='uploads/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
