# Generated by Django 5.0.4 on 2025-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandnotice',
            name='referenceid',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='year_installed',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
